# Generated by Django 3.0.2 on 2020-01-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать?'),
        ),
        migrations.AddField(
            model_name='post',
            name='viewed',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотернно'),
        ),
        migrations.AddField(
            model_name='tag',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Tag', verbose_name='Тег'),
        ),
    ]
